# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: guyberry153@gmail.com
author_name: Guy Berry
contract_name: hackathon
deployment_language: python
preset_name: starter
project_name: hackathon

